name: Deployr CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_DOMAIN: https://saadhit.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger deployment
        id: trigger
        run: |
          JOB_ID=$(curl -s -X POST "${{ env.DEPLOY_DOMAIN }}/deployr/deploy")
          echo "job_id=${JOB_ID}" >> $GITHUB_OUTPUT
        
      - name: Check deployment status
        id: check-status
        run: |
          MAX_ATTEMPTS=100  # 5 minutes (100 * 3 seconds)
          attempt=1
          
          while [ $attempt -le $MAX_ATTEMPTS ]; do
            STATUS=$(curl -s "${{ env.DEPLOY_DOMAIN }}/deployr/status?job_id=${{ steps.trigger.outputs.job_id }}")
            
            echo "Attempt $attempt: Status is $STATUS"
            
            if [ "$STATUS" = "completed" ]; then
              echo "Deployment completed successfully!"
              exit 0
            elif [ "$STATUS" = "failed" ]; then
              echo "Deployment failed!"
              exit 1
            fi
            
            attempt=$((attempt + 1))
            sleep 3
          done
          
          echo "Timeout: Deployment took too long"
          exit 1